### PR TITLE
Allow the RTP latency to be set from the Player Endpoint

### PR DESCRIPTION
**Pull request by kc7bfi**
By default, a 2 second RTP latency is enforced by the gstreamer RTSP player. This change allows the latency to be set on the Player Endpoint. For example, from the kurento-player tutorial, the latency can be set as:

```
    user.setWebRtcEndpoint(webRtcEndpoint);
    String videourl = jsonMessage.get("videourl").getAsString();
    int latency = jsonMessage.get("latency").getAsInt();
    final PlayerEndpoint playerEndpoint = new PlayerEndpoint.Builder(pipeline, videourl).build();
    playerEndpoint.setLatency(latency);
    user.setPlayerEndpoint(playerEndpoint);
    users.put(session.getId(), user);
```

### CODE REVIEW

**Comment by kc7bfi** [comment]
I am not a GIT expert and use mostly SVN. How to I set the correct pre-commit hooks? Also, is there a way to squash all the commits together once I've done the commits so that it is easier for you to review them? I'm not a novice programmer but I'm much more familure with svn than git. Thanks. David

**Comment by jcaden** [comment]
I usually squash all the commits using an interactive rebase:

https://git-scm.com/book/es/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages

Hope that helps.

**Comment by kc7bfi** [comment]
Just wanted to know the status of this pull request. Is it good to go or is there something else I need to do.

**Comment by nugetchar** [comment]
Hi, I'm looking forward this functionality. What is the status of this pull request ? :)

**Comment by jcaden** [comment]
@kc7bfi First you should merge all commits in one to make comments easily to find, because I have added some comments to all of the commits and its hard to read them. Once it is merged (hopefully with the comments solved) I can review it again and merge if everything is OK.

**Comment by kc7bfi** [comment]
Ugh! I tried to run thought the steps in the documentation (I am a SVN person not a GIT person) and it all refers to how to squash the last 'n' commits into one. However, I've already moved on to making more potential changes to the code and I had to re-sync my fork to the latest from the master git repository. Now there are a lot of other commits on top of mine. Would it be possible for you to simply view the unified file changes under the "Files changed" tab? This change is rather small and hopefully it will not be too much work. Its frustrating when the tools get in the way of the actual work of coding.

**Comment by jcaden** [comment]
As there are many modifications to be done I will create a patch to implement this functionality. Thanks for your help.

**Comment by kc7bfi** [comment]
No, it should be good to go. Thanks, David

**Comment by nugetchar** [comment]
Is there anything new regarding this PR ? :)

**Comment by kc7bfi** [comment]
Any idea when this will appear in the master?

**Comment by nugetchar** [comment]
Any idea when this will appear in the master ? We are looking forward this functionality.

**Comment by up2datecyborg** [comment]
Please, are there any news about this pull request?? It's important in our company where we are working with CCTV IP cameras, and cannot afford high latency...
If the code is already ready to be integrated, why do we wait?
It's very very important for us.

**Comment by jcaden** [comment]
I've created a similar patch (https://github.com/Kurento/kms-elements/commit/d31bc5e06d039e7b4564e007aa998249d9ba78ed) with this functionality

**Pull request closed without merging**
