### PR TITLE
Allow the AppSrc pipeline DOT diagram to be returned

### PR DESCRIPTION
**Pull request by kc7bfi**
I needed a way to see how the AppSrc was creating its internal pipeline for debugging a memory issue I was facing. This allows the user to call getElementGstreamerDot() on a PlayerEndpoit to see how the uridecodebin pipeline is setup.

### CODE REVIEW

**Comment by kc7bfi** [comment]
The new commits add a critical fix to process buffering status message from queue2

**Comment by nordri** [comment]
check out

**Comment by kc7bfi** [comment]
Any idea when this may be merged into the main branch and the SNAPSHOT builds?

**Comment by kc7bfi** [comment]
Any idea when this may be merged into the main branch and the SNAPSHOT builds?

**Comment by kc7bfi** [comment]
Any idea when this may be merged into the main branch and the SNAPSHOT builds?

**Comment by kc7bfi** [comment]
I didn't mean to mark this as closed...

**Pull request closed without merging**
