### PR TITLE
SipRtpEndpoint implementation

### PR DESCRIPTION
**Pull request by slabajo**
SipRtpEndpoint is a replacement for RtpEndpoint that allows renegotiation of media. Currently RtpEndpoint once SDP have been negotiated does not allow to renegotiate media. That is, further invocations of generateOffer, processOffer and processAnswer result in an error about the RtpEndpoint already negotiated.

This is a drawback when integrating. among other cases, with SIP VoIP networks that use[ SIP 183](https://tools.ietf.org/html/draft-ietf-sip-183-00) provisional media establishment because in that cases for a single generated offer, remote network can answer back with several SDP answers. Each SDP answer means some media (temporary) between remote endpoint and local RtpEndpoint. Each time a temporary SDP answer is received, old media should be discarded and new media according to the temporary answer should be established.

To this aim, SipRtpEndpoint behaves exactly as an RtpEndpoint but allows to call any of the SDP negotitation APIs (generateOffer, processOffer or processAnswer) any time and as much times as needed. Each time one of this APIs are called, old media is discarded and the correspoding new media is established.

SipRtpEndpoint is implemented as a derived class from BaseRtpEndpoint to provide the same features that RtpEndpoint. And internally is implemented as a RtpEndpoint connected through a pair of PassThrough elements (one for input media and the other for output media). First time SDP is negotiated, that negotiation is delegated on internal RtpEndpoint. Whenever a renegotiation is done, old internal RtpEndpoint is closed and discarded and a new one is instantiated and reconnected to Passthrough elements and negotiation is delegated on that new RtpEndpoint.

The main involved APIs are:

- generateOffer when renegotiation is done using a new generateOffer call, old RtpEndpoint is discarded and just the generateOffer is delegated on the new internal RtpEndpoint.

- processOffer when renegotiation is done using a new processOffer call, old RtpEndpoint is discarded and just the processOffer is delegated on the new internal RtpEndpoint.

- processAnswer when renegotiation is done using a new processAnswer call, is a little bit more complicated, because the answer corresponds to an original offer generated using generateOffer on this same SipRtpEndpoint. Thus local media description should be preserved, mainly with regard to socket ports and SSRC's. So, old RtpEndpoint is discarded, but before being discarded, allocated Sockets and SSRCs are preserved and feed to the new instantiated RtpEndpoint so that local media preserves socket ports and SSRCs as expected. This behaviour also introduces a problem that is, if remote old media is not stopped before renegotiation, as we are preserving sockets, those sockets may be receiving old and new media flows simultaneously. Due to the architecture of RtpEndpoint in KMS this forces to filter out old media in new RtpEndpoint.

This Endpoint also allows for flexibility when negotiating an RTP or SRTP endpoint. This is intended for easy integration with legacy VoIP/SIP networks where you cannot know in advance if the remote endpoint will support SRTP or not.
In that case, the process is as follows:

- To configure an endpoint to be SRTP/RTP agnostic, it must be created with the cryptoAgnostic parameter in the builder set to true. When it is set to true it means that if processing an offer, it will process and accept both offers with RTP/AVP profile and with RTP/SAVP profiles.

- If it also has configured the crypto argument when built, when generating and offer (call to generateOffer), will generate two sets of media lines, one for RTP/AVP profile and the other for RTP/SAVP profile. Thus allowing the remote peer to select which lines it is interested in (secured or not secured). And provide the answer according to the chosen set. It is important to note that the remote peer should also answer to the m lines it is not interested in with the port set to 0

- Thus, if the endpoint is built with agnosticCrypto and crypto information, the offers generated will contain both RTP/AVP and RTP/SAVP lines, and it will accept answers to that offer that should accept a single set of m lines (in those the answer should set the port of those lines to a valid number different from 0), and reject the lines (setting the port of those lines to 0). It is important to note, that if for any reason the answer processed contains valid m lines (port set to a valid number different from 0) for both RTP/AVP and RTP/SAVP lines, the endpoint will just establish one of the set (if possible the one corresponding to RTP/SAVP profile)

### CODE REVIEW

**Comment by prlanzarin** [comment]
This is marvellous stuff. One question, though: why did you opt naming it SipRtpEndpoint instead of something like RtpEndpointV2 or anything like that? Way I see it, it's still a signalling agnostic RTP endpoint, so naming it SipRtpEndpoint might be confusing to newcomers.

**Comment by j1elo** [comment]
As far as I know, this was specifically to add support for some features of SIP-183 that are missing on RtpEndpoint; and actually this orchestrates the dynamic construction & destruction of internal RtpEndpoints whenever a new renegotiation is needed (speaking off the top of my head from explanations that Saul gave me offline, also now that I see it, the description mentions this)

So it would also probably be a bit misleading if we called it `RtpEndpoint2` given that this is actually a "*manager of RtpEndpoints*", but only for the very specific use case of SIP, hence I suggested Saul this name.

**Comment by logcy** [comment]
Hello, I would like to ask when this change will be released

**Comment by logcy** [comment]
I have a required quantity now, which is to use the volte of the mobile phone to connect to the web page, and then use kurento to perform some special processing on the video. I am currently suffering from no good method.

**Comment by alindzon** [comment]
Has this been added?  I don't see it mentioned in the documentation.  I am having an issue with Ice State disconnected intermittently when adding members to a room.  When that happens there is no media on that connection.  So to correct that I want to try to renegotiate.  This looks like the answer.  You would think some kind of retry would just be built-in, or a command to retry the connection.  By the way to get the actual error I had to add this to kurento-utils.js.  It is totally needed to enable all sorts of stuff that is useful.  
            WebRtcPeer.prototype.getPeerConnection = function (index) {
                if (this.peerConnection) {
                    return this.peerConnection;
                }
            };
then in my room.js when in the receiveVideo function i adjusted this
		participant.rtcPeer = new kurentoUtils.WebRtcPeer.WebRtcPeerRecvonly(options,
			function (error) {
				if (error) {
					return console.error(error);
				}
				this.getPeerConnection().oniceconnectionstatechange = function () {...

**Comment by micaelgallego** [comment]
We will start the integration in the following weeks.

**Comment by traoremp** [comment]
Has this been integrated yet ?

**Comment by pgbinup** [comment]
Will this be part  release 6.16.1 ?

**Comment by dpocock** [comment]
@slabajo are there other related pull requests against other repositories in Kurento, GStreamer or elsewhere?

**Comment by dpocock** [comment]
> So it would also probably be a bit misleading if we called it `RtpEndpoint2` given that this is actually a "_manager of RtpEndpoints_", but only for the very specific use case of SIP, hence I suggested Saul this name.

To keep things simple, maybe this element should completely replace RtpEndpoint and therefore it would use the name RtpEndpoint

Having two variations of the endpoint means maintaining more documentation and maybe some confusion for new users.

If the old endpoint code needs to be available as an endpoint then it could be renamed SingleSessionRtpEndpoint or something like that.

**Comment by dpocock** [comment]
@slabajo will this be merged eventually?

**Comment by slabajo** [comment]
Hi Daniel,

Sorry for the late answer, we have been focused on some other priorities.
But we have decided to go to implement SipRtpEndpoint as a pure KMS module,
that is, it can be downloaded separately and added to the KMS server. For
this we need integrate this PR RtpEndpoint library by slabajo · Pull
Request #33 · Kurento/kms-elements (github.com)
<https://github.com/Kurento/kms-elements/pull/33> that allows to build an
RtpEndpoint library that the SipRtpEndpoint can derive from. We hope to
have this PR integrated in the following days and then be released on next
KMS version (probably 6.17). Then you can find the SipRtpEndpont module
here:
naevatec/kms-siprtpendpoint: Kurento SipRtpEndpoint modiule, provides the
capabilities of connecting RTP media flows from a SIP network into Kurento.
Of course it will require some SIP signalling plane not included in this
module. (github.com) <https://github.com/naevatec/kms-siprtpendpoint>










*Saúl Pablo Labajo Izquierdo*
CEO



www.naevatec.com
email:    ***@***.***

mobile:   +34 606 697134

phone:    +34 911 407507



*In accordance with the provisions of the REGULATION (EU) 2016/679 of
protection of personal data, we inform you that the data you provide us
will be incorporated into the treatment system owned by TIKAL TECHNOLOGIES
SL with CIF B85986669 and address located at Calle Chile, Nº 10, 28290 -
Las Rozas de Madrid (Madrid), for the purpose of Advertising and Commercial
Prospecting; other purposes. Your data may be processed by third parties
(they will be responsible for the treatment of your data for a lawful
contractual purpose, for example, our computer maintenance company)
demanding the same level of rights, obligations and established
responsibilities. Your data will be kept for the period strictly necessary.
They will be erased when a time has elapsed without making use of them. You
agree to notify us of any variation in the data. You can exercise the
rights of access, rectification, limitation of treatment, deletion,
portability and opposition to the processing of your personal data by
addressing your request to the postal address indicated above or to the
email ***@***.*** ***@***.***>. You can go to the competent
Control Authority to present the claim that you consider appropriate.*

**Pull request closed without merging**
